//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlegZee.FractalBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OlegZee.FractalBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #define NEXT(x,r) (r * x - r * x * x)
        ///
        ///kernel void Lyapunov(
        ///	constant float* a,
        ///	constant float* b,
        ///	constant float* m,
        ///	global write_only float* t,
        ///	float initialX,
        ///	int warmupCount, int iterationsCount,
        ///	int maskLen, float divider)
        ///{
        ///	int i = get_global_id(0) * 4;
        ///	int j = get_global_id(1);
        ///
        ///	int offset = j * get_global_size(0) * 4 + i;
        ///
        ///	float4 x = (float4)(initialX);
        ///	float4 bv = (float4)(b[i], b[i+1], b[i+2], b[i+3]);
        ///	float4 av = (float4)(a[j]);
        ///	for (int idx = 0; idx &lt; warmupCount [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lyapunov {
            get {
                return ResourceManager.GetString("Lyapunov", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon LyapunovIcon {
            get {
                object obj = ResourceManager.GetObject("LyapunovIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
