<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FractalGpu.Rendering</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cloo.clSharp" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/*.*" />
  </ItemGroup>

</Project>
